### ISSUE TITLE
March 2020 - content update

### ISSUE THREAD

**Issue by DawnmarieDesJardins** [microsoft/MCW-Line-of-business-application-migration#36]
This workshop is scheduled for an update. Opsgility, please review open issues and pull requests.  Update this issue below with changes your team recommends for the workshop for SME review and feedback.

**Comment by paulopsgility** [comment]
Proposed updates 

- Update/patch images for VMs
- Fix passwords everywhere to remove @ character, (fixes issues with non-US keyboards)
- At end of lab, there are steps to install Azure agent on migrated VMs. These don't work because the VMs don't have public IPs.  
- Switch SQL Database to using a private endpoint
- Add new exercise to Include DNS switchover between environments 
- Exercise 1, task 2 – we can pre-create the Hyper-V switch for the migration appliance.
- Exercise 1, Task 3, Step 5: Add a note telling them NOT to make the NIC public (causes assessment to fail)
- Exercise 1, Task 5, Step 12: We have them ssh’ing from Cloud Shell to the WAF, but we should probably do this from the host. It’s not clear why the WAF is exposing SSH to the internet.
- Exercise 2, Task 1: Provide a script to register the RP. They’ve been in the portal a lot already up until this point.
- Exercise 3, Task 9: We have them install the VM agent, but not actually use. Add something (e.g. use the Run Command on one of the Windows VMs) to validate that the agent is in fact working.

**Comment by jtuliani** [comment]
Great list. My only concern is the DNS switchover. We can definitely do it, and it does add value to the lab, and I'm a big fan of DNS!  However it will add time to the lab, and I already find the lab is very long. In many classes where this lab is used, fitting the lab into the time available is already a problem. So adding yet another stage is a concern.

**Comment by TJGitHubUser** [comment]
If you keep SSH, can we direct people to use Chrome instead of IE? Better copy/paste experience.
Check for UI screenshot updates, for example Exercise 1, Task 1, step 2 - screenshot of Azure Migrate Overview blade, and step 7 - Azure Migrate Servers blade
Good idea to pre-create the virtual switch, but keep a note explaining what the script does, as they user would have to do this anyway.
Nice list!

**Comment by jtuliani** [comment]
Everything above addressed in mar-2020-updates branch, EXCEPT

- Haven't added DNS exercise. It requires registering a domain name. We could do this via App Service Domains in the setup template, and it's even zero-cost so long as you clean up the environment within 5 days. However, registering a domain requires personal details (full name, phone number, email address, street address). While most registrars don't verify this info, so we could put in generic values, there are potential legal/compliance issues with doing so. Until this question is resolved, we should hold off.

- Didn't understand the comment "Exercise 1, Task 3, Step 5: Add a note telling them NOT to make the NIC public (causes assessment to fail)". Please check the exercise/task/step numbers and description.

**Comment by DawnmarieDesJardins** [comment]
Closing issue as complete with merge of PR #38
