### ISSUE TITLE
FY22Q1 Updates

### ISSUE THREAD

**Issue by dwnatwick** [microsoft/MCW-Line-of-business-application-migration#70]

**Comment by KitSkin** [comment]
LOB Migrate WDS Updates
* Include discuss of Web Application Firewall either via [App Gateway](https://docs.microsoft.com/en-us/azure/web-application-firewall/ag/ag-overview) or [Front Door](https://docs.microsoft.com/en-us/azure/web-application-firewall/afds/afds-overview)
* Add migration discussion to either [Web App](https://docs.microsoft.com/en-us/azure/migrate/tutorial-app-containerization-aspnet-app-service) or [Containers](https://docs.microsoft.com/en-us/azure/migrate/tutorial-app-containerization-aspnet-kubernetes) from VM
* Include more discussion and key talking points about [Monitor](https://docs.microsoft.com/en-us/azure/azure-monitor/overview) with alerts and dashboards

LOB Migrate HOL
* Improvements
  * Rework Exercise 3; Task 9 to use [App Gateway with WAF](https://docs.microsoft.com/en-us/azure/web-application-firewall/ag/ag-overview) rather than UbuntuWAF VM
    * Rather than have the client work to have Ubuntu VM running the WAF, move just the web VM's and place them behind App Gateway and use built in WAF
  * Rework application to migrate to [Web App](https://docs.microsoft.com/en-us/azure/migrate/tutorial-app-containerization-aspnet-app-service) or [Containers on AKS](https://docs.microsoft.com/en-us/azure/migrate/tutorial-app-containerization-aspnet-kubernetes)
    * With the landing zone work moved to a template to save time, use the time to migrate the web from running on VM to then moving as Web App or Container
    * Develop template to deploy either App Service Plan or AKS for landing zone
    * This could essentially be a PaaS only solution
  * Migrate to use [Azure AD with SQL](https://docs.microsoft.com/en-us/azure/azure-sql/database/authentication-aad-overview) and [Managed Identity](https://docs.microsoft.com/en-us/azure/app-service/app-service-web-tutorial-connect-msi)
    * Assuming the app is moved to Web App or Container, configure SQL Server to use Azure AD integrated authentication
    * Use a Managed Identity to authenticate to the SQL DB from app (either [Web App](https://docs.microsoft.com/en-us/azure/app-service/app-service-web-tutorial-connect-msi) or [AKS](https://docs.microsoft.com/en-us/azure/aks/operator-best-practices-identity#use-pod-managed-identities))
* Resolutions
  * Include resources in setup activities
    * Provide Template of 'Exercise 3 landing zone' for BYOS and integrate into lab environment deployments:
      * SQL Server and Database
      * Virtual Network
      * Storage Account
      * Application Gateway with WAF
      * Azure Bastion
      * Log Analytics Workspace (for Azure Monitor)

**Comment by DawnmarieDesJardins** [comment]
Closing issue with merge of PR #73
